#!/usr/bin/env bash

echo "==create bucket"

if [ -z "$1" ]; then
    echo "there needs to be a name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket --bucket $BUCKET_NAME --create-bucket-configuration LocationConstraint=eu-north-1 --region eu-north-1
