#!/usr/bin/env bash

echo "==put-object"

if [ -z "$1" ]; then
    echo "there needs to be a bucket name"
    exit 1
fi

if [ -z "$2" ]; then
    echo "there needs to be a file name"
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2
OBJECT_KEY = $(basename "$FILENAME")


aws s3api put-object \
--bucket $BUCKET_NAME \
--body $FILENAME \
--key $OBJECT_KEY